#name: Deploy Repo
#
#on:
#  push:
#    paths:
#      - app/**
#    branches:
#      - main
#
#env:
#  AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
#  AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#
#jobs:
#  tf_fmt:
#    name: Deploy Terraform
#    runs-on: ubuntu-latest
#    steps:
#    - uses: hashicorp/setup-terraform@v2
#
#    - name: Checkout Repo
#      uses: actions/checkout@v1
#
#    - name: Terraform Init
#      id: init
#      run: terraform init -input=false -backend-config=vars/personal/backend.hcl
#
#    - name: Terraform Validate
#      id: validate
#      run: terraform validate -no-color
#
#    - name: Terraform Plan
#      id: plan
#      run: terraform plan -input=false -no-color -var-file=vars/common.tfvars -var-file=vars/personal/vars.tfvars
#
#    - name: Terraform Apply
#      id: apply
#      run: terraform apply -input=false -no-color -auto-approve -var-file=vars/common.tfvars -var-file=vars/personal/vars.tfvars