bucket         = "bartparka-personal-edap-terraform-state"
dynamodb_table = "bartparka-personal-terraform-state-lock-dynamo"
profile        = "personal"
key            = "dev-simple-web-app-fargate.tfstate"
region         = "eu-west-2"